<?php

use Illuminate\Database\Seeder;
use App\Departments;
use App\Town;

class TownTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departmentAntioquia = Departments::where('dept_name', 'Antioquia')->first();
        $departmentAntioquia->towns()->saveMany([
            new Town([ 'town_code' => '001', 'town_name' => 'Medellin' ]),
            new Town([ 'town_code' => '002', 'town_name' => 'Abejorral' ]),
            new Town([ 'town_code' => '004', 'town_name' => 'Abriaqui' ]),
            new Town([ 'town_code' => '021', 'town_name' => 'Alejandra' ]),
            new Town([ 'town_code' => '030', 'town_name' => 'Amaga' ]),
            new Town([ 'town_code' => '031', 'town_name' => 'Amalfi' ]),
            new Town([ 'town_code' => '034', 'town_name' => 'Andes' ]),
            new Town([ 'town_code' => '036', 'town_name' => 'Angelopolis' ]),
            new Town([ 'town_code' => '038', 'town_name' => 'Angostura' ]),
            new Town([ 'town_code' => '040', 'town_name' => 'Anori' ]),
            new Town([ 'town_code' => '042', 'town_name' => 'Antioquia' ]),
            new Town([ 'town_code' => '044', 'town_name' => 'Anza' ]),
            new Town([ 'town_code' => '045', 'town_name' => 'Apartado' ]),
            new Town([ 'town_code' => '051', 'town_name' => 'Arboletes' ]),
            new Town([ 'town_code' => '055', 'town_name' => 'Argelia' ]),
            new Town([ 'town_code' => '059', 'town_name' => 'Armenia' ]),
            new Town([ 'town_code' => '079', 'town_name' => 'Barbosa' ]),
            new Town([ 'town_code' => '086', 'town_name' => 'Belmira' ]),
            new Town([ 'town_code' => '088', 'town_name' => 'Bello' ]),
            new Town([ 'town_code' => '091', 'town_name' => 'Betania' ]),
            new Town([ 'town_code' => '093', 'town_name' => 'Betulia' ]),
            new Town([ 'town_code' => '101', 'town_name' => 'Bolivar' ]),
            new Town([ 'town_code' => '107', 'town_name' => 'Briceño' ]),
            new Town([ 'town_code' => '113', 'town_name' => 'Buritica' ]),
            new Town([ 'town_code' => '120', 'town_name' => 'Caceres' ]),
            new Town([ 'town_code' => '125', 'town_name' => 'Caicedo' ]),
            new Town([ 'town_code' => '129', 'town_name' => 'Caldas' ]),
            new Town([ 'town_code' => '134', 'town_name' => 'Campamento' ]),
            new Town([ 'town_code' => '138', 'town_name' => 'Cañasgordas' ]),
            new Town([ 'town_code' => '142', 'town_name' => 'Caracoli' ]),
            new Town([ 'town_code' => '145', 'town_name' => 'Caramanta' ]),
            new Town([ 'town_code' => '147', 'town_name' => 'Carepa' ]),
            new Town([ 'town_code' => '148', 'town_name' => 'Carmen de Viboral' ]),
            new Town([ 'town_code' => '150', 'town_name' => 'Carolina' ]),
            new Town([ 'town_code' => '154', 'town_name' => 'Caucasia' ]),
            new Town([ 'town_code' => '172', 'town_name' => 'Chigorodo' ]),
            new Town([ 'town_code' => '190', 'town_name' => 'Cisneros' ]),
            new Town([ 'town_code' => '206', 'town_name' => 'Concepcion' ]),
            new Town([ 'town_code' => '209', 'town_name' => 'Concordia' ]),
            new Town([ 'town_code' => '212', 'town_name' => 'Copacabana' ]),
            new Town([ 'town_code' => '234', 'town_name' => 'Dabeiba' ]),
            new Town([ 'town_code' => '237', 'town_name' => 'Don Matias' ]),
            new Town([ 'town_code' => '240', 'town_name' => 'Ebejico' ]),
            new Town([ 'town_code' => '250', 'town_name' => 'El Bagre' ]),
            new Town([ 'town_code' => '264', 'town_name' => 'Entrerrios' ]),
            new Town([ 'town_code' => '266', 'town_name' => 'Envigado' ]),
            new Town([ 'town_code' => '282', 'town_name' => 'Fredonia' ]),
            new Town([ 'town_code' => '284', 'town_name' => 'Frontino' ]),
            new Town([ 'town_code' => '306', 'town_name' => 'Giraldo' ]),
            new Town([ 'town_code' => '308', 'town_name' => 'Girardota' ]),
            new Town([ 'town_code' => '310', 'town_name' => 'Gomez Plata' ]),
            new Town([ 'town_code' => '313', 'town_name' => 'Granada' ]),
            new Town([ 'town_code' => '315', 'town_name' => 'Guadalupe' ]),
            new Town([ 'town_code' => '318', 'town_name' => 'Guarne' ]),
            new Town([ 'town_code' => '321', 'town_name' => 'Guatape' ]),
            new Town([ 'town_code' => '347', 'town_name' => 'Heliconia' ]),
            new Town([ 'town_code' => '353', 'town_name' => 'Hispania' ]),
            new Town([ 'town_code' => '360', 'town_name' => 'Itagui' ]),
            new Town([ 'town_code' => '361', 'town_name' => 'Ituango' ]),
            new Town([ 'town_code' => '364', 'town_name' => 'Jardin' ]),
            new Town([ 'town_code' => '368', 'town_name' => 'Jerico' ]),
            new Town([ 'town_code' => '376', 'town_name' => 'La Ceja' ]),
            new Town([ 'town_code' => '380', 'town_name' => 'La Estrella' ]),
            new Town([ 'town_code' => '390', 'town_name' => 'La Pintada' ]),
            new Town([ 'town_code' => '400', 'town_name' => 'La Union' ]),
            new Town([ 'town_code' => '411', 'town_name' => 'Liborina' ]),
            new Town([ 'town_code' => '425', 'town_name' => 'Maceo' ]),
            new Town([ 'town_code' => '440', 'town_name' => 'Marinilla' ]),
            new Town([ 'town_code' => '467', 'town_name' => 'Montebello' ]),
            new Town([ 'town_code' => '475', 'town_name' => 'Murindo' ]),
            new Town([ 'town_code' => '480', 'town_name' => 'Mutata' ]),
            new Town([ 'town_code' => '483', 'town_name' => 'Nariño' ]),
            new Town([ 'town_code' => '490', 'town_name' => 'Necocli' ]),
            new Town([ 'town_code' => '495', 'town_name' => 'Nechi' ]),
            new Town([ 'town_code' => '501', 'town_name' => 'Olaya' ]),
            new Town([ 'town_code' => '541', 'town_name' => 'Peñol' ]),
            new Town([ 'town_code' => '543', 'town_name' => 'Peque' ]),
            new Town([ 'town_code' => '576', 'town_name' => 'Pueblo Rico' ]),
            new Town([ 'town_code' => '579', 'town_name' => 'Puerto Berrio' ]),
            new Town([ 'town_code' => '585', 'town_name' => 'Puerto Nare' ]),
            new Town([ 'town_code' => '591', 'town_name' => 'Puerto Triunfo' ]),
            new Town([ 'town_code' => '604', 'town_name' => 'Remedios' ]),
            new Town([ 'town_code' => '607', 'town_name' => 'Retiro' ]),
            new Town([ 'town_code' => '615', 'town_name' => 'Rionegro' ]),
            new Town([ 'town_code' => '628', 'town_name' => 'Sabanalarga' ]),
            new Town([ 'town_code' => '631', 'town_name' => 'Sabaneta' ]),
            new Town([ 'town_code' => '642', 'town_name' => 'Salgar' ]),
            new Town([ 'town_code' => '647', 'town_name' => 'San Andres' ]),
            new Town([ 'town_code' => '649', 'town_name' => 'San Carlos' ]),
            new Town([ 'town_code' => '652', 'town_name' => 'San Francisco' ]),
            new Town([ 'town_code' => '656', 'town_name' => 'San Jeronimo' ]),
            new Town([ 'town_code' => '658', 'town_name' => 'San Jose de la Montaña' ]),
            new Town([ 'town_code' => '659', 'town_name' => 'San Juan de Uraba' ]),
            new Town([ 'town_code' => '660', 'town_name' => 'San Luis' ]),
            new Town([ 'town_code' => '664', 'town_name' => 'San Pedro' ]),
            new Town([ 'town_code' => '665', 'town_name' => 'San Pedro de Uraba' ]),
            new Town([ 'town_code' => '667', 'town_name' => 'San Rafael' ]),
            new Town([ 'town_code' => '670', 'town_name' => 'San Roque' ]),
            new Town([ 'town_code' => '674', 'town_name' => 'San Vicente' ]),
            new Town([ 'town_code' => '679', 'town_name' => 'Santa Barbara' ]),
            new Town([ 'town_code' => '686', 'town_name' => 'Santa Rosa de Osos' ]),
            new Town([ 'town_code' => '690', 'town_name' => 'Santo Domingo' ]),
            new Town([ 'town_code' => '697', 'town_name' => 'Santuario' ]),
            new Town([ 'town_code' => '736', 'town_name' => 'Segovia' ]),
            new Town([ 'town_code' => '756', 'town_name' => 'Sonson' ]),
            new Town([ 'town_code' => '761', 'town_name' => 'Sopetran' ]),
            new Town([ 'town_code' => '789', 'town_name' => 'Tamesis' ]),
            new Town([ 'town_code' => '790', 'town_name' => 'Taraza' ]),
            new Town([ 'town_code' => '792', 'town_name' => 'Tarso' ]),
            new Town([ 'town_code' => '809', 'town_name' => 'Titiribi' ]),
            new Town([ 'town_code' => '819', 'town_name' => 'Toledo' ]),
            new Town([ 'town_code' => '837', 'town_name' => 'Turbo' ]),
            new Town([ 'town_code' => '842', 'town_name' => 'Uramita' ]),
            new Town([ 'town_code' => '847', 'town_name' => 'Urrao' ]),
            new Town([ 'town_code' => '854', 'town_name' => 'Valdivia' ]),
            new Town([ 'town_code' => '856', 'town_name' => 'Valparaiso' ]),
            new Town([ 'town_code' => '858', 'town_name' => 'Vegachi' ]),
            new Town([ 'town_code' => '861', 'town_name' => 'Venecia' ]),
            new Town([ 'town_code' => '873', 'town_name' => 'Vigia del Fuerte' ]),
            new Town([ 'town_code' => '885', 'town_name' => 'Yali' ]),
            new Town([ 'town_code' => '887', 'town_name' => 'Yarumal' ]),
            new Town([ 'town_code' => '890', 'town_name' => 'Yolombo' ]),
            new Town([ 'town_code' => '893', 'town_name' => 'Yondo' ]),
            new Town([ 'town_code' => '895', 'town_name' => 'Zaragosa' ]),
        ]);

        $atlantico  = Departments::where('dept_name', 'Atlantico')->first();
        $atlantico->towns()->saveMany([
            new Town([ 'town_code' => '001' , 'town_name' => 'Barranquilla' ]),
            new Town([ 'town_code' => '078' , 'town_name' => 'Baranoa' ]),
            new Town([ 'town_code' => '137' , 'town_name' => 'Campo de la Cruz' ]),
            new Town([ 'town_code' => '141' , 'town_name' => 'Candelaria' ]),
            new Town([ 'town_code' => '296' , 'town_name' => 'Galapa' ]),
            new Town([ 'town_code' => '372' , 'town_name' => 'Juan de Acosta' ]),
            new Town([ 'town_code' => '421' , 'town_name' => 'Luruaco' ]),
            new Town([ 'town_code' => '433' , 'town_name' => 'Malambo' ]),
            new Town([ 'town_code' => '436' , 'town_name' => 'Manati' ]),
            new Town([ 'town_code' => '520' , 'town_name' => 'Palmar de Varela' ]),
            new Town([ 'town_code' => '549' , 'town_name' => 'Piojo' ]),
            new Town([ 'town_code' => '558' , 'town_name' => 'Polo Nuevo' ]),
            new Town([ 'town_code' => '560' , 'town_name' => 'Ponedera' ]),
            new Town([ 'town_code' => '573' , 'town_name' => 'Puerto Colombia' ]),
            new Town([ 'town_code' => '606' , 'town_name' => 'Repelon' ]),
            new Town([ 'town_code' => '634' , 'town_name' => 'Sabanagrande' ]),
            new Town([ 'town_code' => '638' , 'town_name' => 'Sabanalarga' ]),
            new Town([ 'town_code' => '675' , 'town_name' => 'Santa Lucia' ]),
            new Town([ 'town_code' => '685' , 'town_name' => 'Santo Tomas' ]),
            new Town([ 'town_code' => '758' , 'town_name' => 'Soledad' ]),
            new Town([ 'town_code' => '770' , 'town_name' => 'Suan' ]),
            new Town([ 'town_code' => '832' , 'town_name' => 'Tubara' ]),
            new Town([ 'town_code' => '849' , 'town_name' => 'Usiacuri' ])
        ]);

        $bogota  = Departments::where('dept_name', 'Bogota')->first();
        $bogota->towns()->saveMany([
            new Town(['town_code' => '001' , 'town_name' => 'Santa Fe de Bogota'])
        ]);

        $bolivar  = Departments::where('dept_name', 'Bolivar')->first();
        $bolivar->towns()->saveMany([
            new Town(['town_code' => '001' , 'town_name' => 'Cartagena' ]),
            new Town(['town_code' => '006' , 'town_name' => 'Achi' ]),
            new Town(['town_code' => '030' , 'town_name' => 'Altos de Rosario' ]),
            new Town(['town_code' => '042' , 'town_name' => 'Arenal' ]),
            new Town(['town_code' => '052' , 'town_name' => 'Arjona' ]),
            new Town(['town_code' => '062' , 'town_name' => 'Arroyohondo' ]),
            new Town(['town_code' => '074' , 'town_name' => 'Barranco de Loba' ]),
            new Town(['town_code' => '140' , 'town_name' => 'Calamar' ]),
            new Town(['town_code' => '160' , 'town_name' => 'Cantagallo' ]),
            new Town(['town_code' => '188' , 'town_name' => 'Cicuco' ]),
            new Town(['town_code' => '212' , 'town_name' => 'Cordoba' ]),
            new Town(['town_code' => '222' , 'town_name' => 'Clemencia' ]),
            new Town(['town_code' => '244' , 'town_name' => 'Carmen de Bolivar' ]),
            new Town(['town_code' => '248' , 'town_name' => 'El Guamo' ]),
            new Town(['town_code' => '268' , 'town_name' => 'El Peñon' ]),
            new Town(['town_code' => '300' , 'town_name' => 'Hatillo de Loba' ]),
            new Town(['town_code' => '430' , 'town_name' => 'Magangue' ]),
            new Town(['town_code' => '433' , 'town_name' => 'Mahates' ]),
            new Town(['town_code' => '440' , 'town_name' => 'Margarita' ]),
            new Town(['town_code' => '442' , 'town_name' => 'Maria la Baja' ]),
            new Town(['town_code' => '458' , 'town_name' => 'Montecristo' ]),
            new Town(['town_code' => '468' , 'town_name' => 'Mompos' ]),
            new Town(['town_code' => '473' , 'town_name' => 'Morales' ]),
            new Town(['town_code' => '549' , 'town_name' => 'Pinillos' ]),
            new Town(['town_code' => '580' , 'town_name' => 'Regidor' ]),
            new Town(['town_code' => '600' , 'town_name' => 'Rio Viejo' ]),
            new Town(['town_code' => '620' , 'town_name' => 'San Cristobal' ]),
            new Town(['town_code' => '647' , 'town_name' => 'San Estanislao' ]),
            new Town(['town_code' => '650' , 'town_name' => 'San Fernando' ]),
            new Town(['town_code' => '654' , 'town_name' => 'San Jacinto' ]),
            new Town(['town_code' => '655' , 'town_name' => 'San Jacinto del Cauca' ]),
            new Town(['town_code' => '657' , 'town_name' => 'San Juan Nepomuceno' ]),
            new Town(['town_code' => '667' , 'town_name' => 'San Martin de Loba' ]),
            new Town(['town_code' => '670' , 'town_name' => 'San Pablo' ]),
            new Town(['town_code' => '673' , 'town_name' => 'Santa Catalina' ]),
            new Town(['town_code' => '683' , 'town_name' => 'Santa Rosa' ]),
            new Town(['town_code' => '688' , 'town_name' => 'Santa Rosa del Sur' ]),
            new Town(['town_code' => '744' , 'town_name' => 'Simiti' ]),
            new Town(['town_code' => '760' , 'town_name' => 'Soplaviento' ]),
            new Town(['town_code' => '780' , 'town_name' => 'Talaigua Nuevo' ]),
            new Town(['town_code' => '810' , 'town_name' => 'Tiquisio' ]),
            new Town(['town_code' => '836' , 'town_name' => 'Turbaco' ]),
            new Town(['town_code' => '838' , 'town_name' => 'Turbana' ]),
            new Town(['town_code' => '873' , 'town_name' => 'Villanueva' ]),
            new Town(['town_code' => '894' , 'town_name' => 'Zambrano' ])
        ]);

        $boyaca  = Departments::where('dept_name', 'Boyaca')->first();
        $boyaca->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Tunja' ]),
            new Town(['town_code' => '022', 'town_name' => 'Almeida' ]),
            new Town(['town_code' => '047', 'town_name' => 'Aquitania' ]),
            new Town(['town_code' => '051', 'town_name' => 'Arcabuco' ]),
            new Town(['town_code' => '087', 'town_name' => 'Belen' ]),
            new Town(['town_code' => '090', 'town_name' => 'Berbeo' ]),
            new Town(['town_code' => '092', 'town_name' => 'Beteitiva' ]),
            new Town(['town_code' => '097', 'town_name' => 'Boavita' ]),
            new Town(['town_code' => '104', 'town_name' => 'Boyaca' ]),
            new Town(['town_code' => '106', 'town_name' => 'Briceño' ]),
            new Town(['town_code' => '109', 'town_name' => 'Buenavista' ]),
            new Town(['town_code' => '114', 'town_name' => 'Busbanza' ]),
            new Town(['town_code' => '131', 'town_name' => 'Caldas' ]),
            new Town(['town_code' => '135', 'town_name' => 'Campohermoso' ]),
            new Town(['town_code' => '162', 'town_name' => 'Cerinza' ]),
            new Town(['town_code' => '172', 'town_name' => 'Chinavita' ]),
            new Town(['town_code' => '176', 'town_name' => 'Chiquinquira' ]),
            new Town(['town_code' => '180', 'town_name' => 'Chiscas' ]),
            new Town(['town_code' => '183', 'town_name' => 'Chita' ]),
            new Town(['town_code' => '185', 'town_name' => 'Chitaraque' ]),
            new Town(['town_code' => '187', 'town_name' => 'Chivata' ]),
            new Town(['town_code' => '189', 'town_name' => 'Cienega' ]),
            new Town(['town_code' => '204', 'town_name' => 'Combita' ]),
            new Town(['town_code' => '212', 'town_name' => 'Coper' ]),
            new Town(['town_code' => '215', 'town_name' => 'Corrales' ]),
            new Town(['town_code' => '218', 'town_name' => 'Covarachia' ]),
            new Town(['town_code' => '223', 'town_name' => 'Cubara' ]),
            new Town(['town_code' => '224', 'town_name' => 'Cucaita' ]),
            new Town(['town_code' => '226', 'town_name' => 'Cuitiva' ]),
            new Town(['town_code' => '232', 'town_name' => 'Chiquisa' ]),
            new Town(['town_code' => '236', 'town_name' => 'Chivor' ]),
            new Town(['town_code' => '238', 'town_name' => 'Duitama' ]),
            new Town(['town_code' => '244', 'town_name' => 'El Cocuy' ]),
            new Town(['town_code' => '248', 'town_name' => 'El Espino' ]),
            new Town(['town_code' => '272', 'town_name' => 'Firavitoba' ]),
            new Town(['town_code' => '276', 'town_name' => 'Floresta' ]),
            new Town(['town_code' => '293', 'town_name' => 'Gachantiva' ]),
            new Town(['town_code' => '296', 'town_name' => 'Gameza' ]),
            new Town(['town_code' => '299', 'town_name' => 'Garagoa' ]),
            new Town(['town_code' => '317', 'town_name' => 'Guacamayas' ]),
            new Town(['town_code' => '322', 'town_name' => 'Guateque' ]),
            new Town(['town_code' => '325', 'town_name' => 'Guayata' ]),
            new Town(['town_code' => '332', 'town_name' => 'Guican' ]),
            new Town(['town_code' => '362', 'town_name' => 'Iza' ]),
            new Town(['town_code' => '367', 'town_name' => 'Jenesano' ]),
            new Town(['town_code' => '368', 'town_name' => 'Jerico' ]),
            new Town(['town_code' => '377', 'town_name' => 'Labranzagrande' ]),
            new Town(['town_code' => '380', 'town_name' => 'La Capilla' ]),
            new Town(['town_code' => '401', 'town_name' => 'La Victoria' ]),
            new Town(['town_code' => '403', 'town_name' => 'La Uvita' ]),
            new Town(['town_code' => '407', 'town_name' => 'Villa de Leiva' ]),
            new Town(['town_code' => '425', 'town_name' => 'Macanal' ]),
            new Town(['town_code' => '442', 'town_name' => 'Maripi' ]),
            new Town(['town_code' => '455', 'town_name' => 'Miraflores' ]),
            new Town(['town_code' => '464', 'town_name' => 'Mongua' ]),
            new Town(['town_code' => '466', 'town_name' => 'Mongui' ]),
            new Town(['town_code' => '469', 'town_name' => 'Moniquira' ]),
            new Town(['town_code' => '476', 'town_name' => 'Motavita' ]),
            new Town(['town_code' => '480', 'town_name' => 'Muzo' ]),
            new Town(['town_code' => '491', 'town_name' => 'Nobsa' ]),
            new Town(['town_code' => '494', 'town_name' => 'Nuevo Colon' ]),
            new Town(['town_code' => '500', 'town_name' => 'Oicata' ]),
            new Town(['town_code' => '507', 'town_name' => 'Pachavita' ]),
            new Town(['town_code' => '514', 'town_name' => 'Paez' ]),
            new Town(['town_code' => '516', 'town_name' => 'Paipa' ]),
            new Town(['town_code' => '518', 'town_name' => 'Pajarito' ]),
            new Town(['town_code' => '522', 'town_name' => 'Panqueba' ]),
            new Town(['town_code' => '531', 'town_name' => 'Pauna' ]),
            new Town(['town_code' => '533', 'town_name' => 'Paya' ]),
            new Town(['town_code' => '537', 'town_name' => 'Paz del Rio' ]),
            new Town(['town_code' => '542', 'town_name' => 'Pesca' ]),
            new Town(['town_code' => '550', 'town_name' => 'Pisba' ]),
            new Town(['town_code' => '572', 'town_name' => 'Puerto Boyaca' ]),
            new Town(['town_code' => '580', 'town_name' => 'Quipama' ]),
            new Town(['town_code' => '599', 'town_name' => 'Ramiriqui' ]),
            new Town(['town_code' => '600', 'town_name' => 'Raquira' ]),
            new Town(['town_code' => '621', 'town_name' => 'Rondon' ]),
            new Town(['town_code' => '632', 'town_name' => 'Saboya' ]),
            new Town(['town_code' => '638', 'town_name' => 'Sachica' ]),
            new Town(['town_code' => '646', 'town_name' => 'Samaca' ]),
            new Town(['town_code' => '660', 'town_name' => 'San Eduardo' ]),
            new Town(['town_code' => '664', 'town_name' => 'San Jose de Pare' ]),
            new Town(['town_code' => '667', 'town_name' => 'San Luis de Gaceno' ]),
            new Town(['town_code' => '673', 'town_name' => 'San Mateo' ]),
            new Town(['town_code' => '676', 'town_name' => 'San Miguel de Sema' ]),
            new Town(['town_code' => '681', 'town_name' => 'San Pablo de Borbur' ]),
            new Town(['town_code' => '686', 'town_name' => 'Santana' ]),
            new Town(['town_code' => '690', 'town_name' => 'Santa Maria' ]),
            new Town(['town_code' => '693', 'town_name' => 'Santa Rosa de Viterbo' ]),
            new Town(['town_code' => '696', 'town_name' => 'Santa Sofia' ]),
            new Town(['town_code' => '720', 'town_name' => 'Sativanorte' ]),
            new Town(['town_code' => '723', 'town_name' => 'Sativasur' ]),
            new Town(['town_code' => '740', 'town_name' => 'Siachoque' ]),
            new Town(['town_code' => '753', 'town_name' => 'Soata' ]),
            new Town(['town_code' => '755', 'town_name' => 'Socota' ]),
            new Town(['town_code' => '757', 'town_name' => 'Socha' ]),
            new Town(['town_code' => '759', 'town_name' => 'Sogamoso' ]),
            new Town(['town_code' => '761', 'town_name' => 'Somondoco' ]),
            new Town(['town_code' => '762', 'town_name' => 'Sora' ]),
            new Town(['town_code' => '763', 'town_name' => 'Sotaquira' ]),
            new Town(['town_code' => '764', 'town_name' => 'Soraca' ]),
            new Town(['town_code' => '774', 'town_name' => 'Susacon' ]),
            new Town(['town_code' => '776', 'town_name' => 'Sutamarchan' ]),
            new Town(['town_code' => '778', 'town_name' => 'Sutatenza' ]),
            new Town(['town_code' => '790', 'town_name' => 'Tasco' ]),
            new Town(['town_code' => '798', 'town_name' => 'Tenza' ]),
            new Town(['town_code' => '804', 'town_name' => 'Tibana' ]),
            new Town(['town_code' => '806', 'town_name' => 'Tibasosa' ]),
            new Town(['town_code' => '808', 'town_name' => 'Tinjaca' ]),
            new Town(['town_code' => '810', 'town_name' => 'Tipacoque' ]),
            new Town(['town_code' => '814' , 'town_name'  => 'Toca' ]),
            new Town(['town_code' => '816', 'town_name' => 'Togui' ]),
            new Town(['town_code' => '820', 'town_name' => 'Topaga' ]),
            new Town(['town_code' => '822', 'town_name' => 'Tota' ]),
            new Town(['town_code' => '832', 'town_name' => 'Tunungua' ]),
            new Town(['town_code' => '835', 'town_name' => 'Turmeque' ]),
            new Town(['town_code' => '837', 'town_name' => 'Tuta' ]),
            new Town(['town_code' => '839', 'town_name' => 'Tutasa' ]),
            new Town(['town_code' => '842', 'town_name' => 'Umbita' ]),
            new Town(['town_code' => '861', 'town_name' => 'Ventaquemada' ]),
            new Town(['town_code' => '879', 'town_name' => 'Viracacha' ]),
            new Town(['town_code' => '897', 'town_name' => 'Zetaquira' ])
        ]);

        $caldas  = Departments::where('dept_name', 'Caldas')->first();
        $caldas->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Manizales' ]),
            new Town(['town_code' => '013', 'town_name' => 'Aguadas' ]),
            new Town(['town_code' => '042', 'town_name' => 'Anserma' ]),
            new Town(['town_code' => '050', 'town_name' => 'Aranzazu' ]),
            new Town(['town_code' => '088', 'town_name' => 'Belalcazar' ]),
            new Town(['town_code' => '174', 'town_name' => 'Chinchina' ]),
            new Town(['town_code' => '272', 'town_name' => 'Filadelfia' ]),
            new Town(['town_code' => '380', 'town_name' => 'La Dorada' ]),
            new Town(['town_code' => '388', 'town_name' => 'La Merced' ]),
            new Town(['town_code' => '433', 'town_name' => 'Manzanares' ]),
            new Town(['town_code' => '442', 'town_name' => 'Marmato' ]),
            new Town(['town_code' => '444', 'town_name' => 'Marquetalia' ]),
            new Town(['town_code' => '446', 'town_name' => 'Marulanda' ]),
            new Town(['town_code' => '486', 'town_name' => 'Neira' ]),
            new Town(['town_code' => '495', 'town_name' => 'Norcasia' ]),
            new Town(['town_code' => '513', 'town_name' => 'Pacora' ]),
            new Town(['town_code' => '524', 'town_name' => 'Palestina' ]),
            new Town(['town_code' => '541', 'town_name' => 'Pensilvania' ]),
            new Town(['town_code' => '614', 'town_name' => 'Riosucio' ]),
            new Town(['town_code' => '616', 'town_name' => 'Risaralda' ]),
            new Town(['town_code' => '653', 'town_name' => 'Salamina' ]),
            new Town(['town_code' => '662', 'town_name' => 'Samana' ]),
            new Town(['town_code' => '665', 'town_name' => 'San Jose' ]),
            new Town(['town_code' => '777', 'town_name' => 'Supia' ]),
            new Town(['town_code' => '867', 'town_name' => 'Victoria' ]),
            new Town(['town_code' => '873', 'town_name' => 'Villamaria' ]),
            new Town(['town_code' => '877', 'town_name' => 'Viterbo' ])
        ]);

        $caqueta  = Departments::where('dept_name', 'Caqueta')->first();
        $caqueta->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Florencia' ]),
            new Town(['town_code' => '029', 'town_name' => 'Albania' ]),
            new Town(['town_code' => '094', 'town_name' => 'Belen de los Andaquies' ]),
            new Town(['town_code' => '150', 'town_name' => 'Cartagena del Chaira' ]),
            new Town(['town_code' => '205', 'town_name' => 'Curillo' ]),
            new Town(['town_code' => '247', 'town_name' => 'El Doncello' ]),
            new Town(['town_code' => '256', 'town_name' => 'El Paujil' ]),
            new Town(['town_code' => '410', 'town_name' => 'La Montañita' ]),
            new Town(['town_code' => '460', 'town_name' => 'Milan' ]),
            new Town(['town_code' => '479', 'town_name' => 'Morelia' ]),
            new Town(['town_code' => '592', 'town_name' => 'Puerto Rico' ]),
            new Town(['town_code' => '610', 'town_name' => 'San Jose de Fragua' ]),
            new Town(['town_code' => '753', 'town_name' => 'San Vicente del Caguan' ]),
            new Town(['town_code' => '756', 'town_name' => 'Solano' ]),
            new Town(['town_code' => '785', 'town_name' => 'Solita' ]),
            new Town(['town_code' => '860', 'town_name' => 'Valparaiso' ])
        ]);

        $cauca  = Departments::where('dept_name', 'Cauca')->first();
        $cauca->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Popayan' ]),
            new Town(['town_code' => '022', 'town_name' => 'Almaguer' ]),
            new Town(['town_code' => '050', 'town_name' => 'Argelia' ]),
            new Town(['town_code' => '075', 'town_name' => 'Balboa' ]),
            new Town(['town_code' => '100', 'town_name' => 'Bolivar' ]),
            new Town(['town_code' => '110', 'town_name' => 'Buenos Aires' ]),
            new Town(['town_code' => '130', 'town_name' => 'Cajibio' ]),
            new Town(['town_code' => '137', 'town_name' => 'Caldono' ]),
            new Town(['town_code' => '142', 'town_name' => 'Caloto' ]),
            new Town(['town_code' => '212', 'town_name' => 'Corinto' ]),
            new Town(['town_code' => '256', 'town_name' => 'El Tambo' ]),
            new Town(['town_code' => '290', 'town_name' => 'Florencia' ]),
            new Town(['town_code' => '318', 'town_name' => 'Guapi' ]),
            new Town(['town_code' => '355', 'town_name' => 'Inza' ]),
            new Town(['town_code' => '364', 'town_name' => 'Jambalo' ]),
            new Town(['town_code' => '392', 'town_name' => 'La Sierra' ]),
            new Town(['town_code' => '397', 'town_name' => 'La Vega' ]),
            new Town(['town_code' => '418', 'town_name' => 'Lopez' ]),
            new Town(['town_code' => '450', 'town_name' => 'Mercaderes' ]),
            new Town(['town_code' => '455', 'town_name' => 'Miranda' ]),
            new Town(['town_code' => '473', 'town_name' => 'Morales' ]),
            new Town(['town_code' => '513', 'town_name' => 'Padilla' ]),
            new Town(['town_code' => '517', 'town_name' => 'Paez' ]),
            new Town(['town_code' => '532', 'town_name' => 'Patia' ]),
            new Town(['town_code' => '533', 'town_name' => 'Piamonte' ]),
            new Town(['town_code' => '548', 'town_name' => 'Piendamo' ]),
            new Town(['town_code' => '573', 'town_name' => 'Puerto Tejada' ]),
            new Town(['town_code' => '585', 'town_name' => 'Purace' ]),
            new Town(['town_code' => '622', 'town_name' => 'Rosas' ]),
            new Town(['town_code' => '693', 'town_name' => 'San Sebastian' ]),
            new Town(['town_code' => '698', 'town_name' => 'Santander de Quilichao' ]),
            new Town(['town_code' => '701', 'town_name' => 'Santa Rosa' ]),
            new Town(['town_code' => '743', 'town_name' => 'Silvia' ]),
            new Town(['town_code' => '760', 'town_name' => 'Sotara' ]),
            new Town(['town_code' => '780', 'town_name' => 'Suarez' ]),
            new Town(['town_code' => '807', 'town_name' => 'Timbio' ]),
            new Town(['town_code' => '809', 'town_name' => 'Timbiqui' ]),
            new Town(['town_code' => '821', 'town_name' => 'Toribio' ]),
            new Town(['town_code' => '824', 'town_name' => 'Totoro' ]),
            new Town(['town_code' => '845', 'town_name' => 'Villarica' ])
        ]);

        $cesar  = Departments::where('dept_name', 'Cesar')->first();
        $cesar->towns()->saveMany([
            new Town(['town_code' => '001' , 'town_name' => 'Valledupar' ]),
            new Town(['town_code' => '011' , 'town_name' => 'Aguachica' ]),
            new Town(['town_code' => '013' , 'town_name' => 'Agustin Codazzi' ]),
            new Town(['town_code' => '032' , 'town_name' => 'Astrea' ]),
            new Town(['town_code' => '045' , 'town_name' => 'Becerril' ]),
            new Town(['town_code' => '060' , 'town_name' => 'Bosconia' ]),
            new Town(['town_code' => '175' , 'town_name' => 'Chimichagua' ]),
            new Town(['town_code' => '178' , 'town_name' => 'Chiriguana' ]),
            new Town(['town_code' => '228' , 'town_name' => 'Curumani' ]),
            new Town(['town_code' => '238' , 'town_name' => 'El Copey' ]),
            new Town(['town_code' => '250' , 'town_name' => 'El Paso' ]),
            new Town(['town_code' => '295' , 'town_name' => 'Gamarra' ]),
            new Town(['town_code' => '310' , 'town_name' => 'Gonzalez' ]),
            new Town(['town_code' => '383' , 'town_name' => 'La Gloria' ]),
            new Town(['town_code' => '400' , 'town_name' => 'La Jagua Ibirico' ]),
            new Town(['town_code' => '443' , 'town_name' => 'Manaure' ]),
            new Town(['town_code' => '517' , 'town_name' => 'Pailitas' ]),
            new Town(['town_code' => '550' , 'town_name' => 'Pelaya' ]),
            new Town(['town_code' => '570' , 'town_name' => 'Pueblo Bello' ]),
            new Town(['town_code' => '614' , 'town_name' => 'Rio de Oro' ]),
            new Town(['town_code' => '621' , 'town_name' => 'La Paz' ]),
            new Town(['town_code' => '710' , 'town_name' => 'San Alberto' ]),
            new Town(['town_code' => '750' , 'town_name' => 'San Diego' ]),
            new Town(['town_code' => '770' , 'town_name' => 'San Martin' ]),
            new Town(['town_code' => '787' , 'town_name' => 'Tamalameque' ])
        ]);

        $cordova  = Departments::where('dept_name', 'Cordoba')->first();
        $cordova->towns()->saveMany([
            new Town(['town_code' => '001' , 'town_name' => 'Monteria' ]),
            new Town(['town_code' => '068' , 'town_name' => 'Ayapel' ]),
            new Town(['town_code' => '079' , 'town_name' => 'Buenvista' ]),
            new Town(['town_code' => '090' , 'town_name' => 'Canalete' ]),
            new Town(['town_code' => '162' , 'town_name' => 'Cerete' ]),
            new Town(['town_code' => '168' , 'town_name' => 'Chima' ]),
            new Town(['town_code' => '182' , 'town_name' => 'Chinu' ]),
            new Town(['town_code' => '189' , 'town_name' => 'Cienaga de Oro' ]),
            new Town(['town_code' => '300' , 'town_name' => 'Cotorra' ]),
            new Town(['town_code' => '350' , 'town_name' => 'La Apartada' ]),
            new Town(['town_code' => '417' , 'town_name' => 'Lorica' ]),
            new Town(['town_code' => '419' , 'town_name' => 'Los Cordobas' ]),
            new Town(['town_code' => '464' , 'town_name' => 'Momil' ]),
            new Town(['town_code' => '466' , 'town_name' => 'Montelibiano' ]),
            new Town(['town_code' => '500' , 'town_name' => 'Moñitos' ]),
            new Town(['town_code' => '555' , 'town_name' => 'Planeta Rica' ]),
            new Town(['town_code' => '570' , 'town_name' => 'Pueblo Nuevo' ]),
            new Town(['town_code' => '574' , 'town_name' => 'Puerto Escondido' ]),
            new Town(['town_code' => '580' , 'town_name' => 'Puerto Libertador' ]),
            new Town(['town_code' => '586' , 'town_name' => 'Purisima' ]),
            new Town(['town_code' => '660' , 'town_name' => 'Sahagun' ]),
            new Town(['town_code' => '670' , 'town_name' => 'San Andres Sotavento' ]),
            new Town(['town_code' => '672' , 'town_name' => 'San Antero' ]),
            new Town(['town_code' => '675' , 'town_name'  => 'San Bernardo del Viento' ]),
            new Town(['town_code' => '678' , 'town_name' => 'San Carlos' ]),
            new Town(['town_code' => '686' , 'town_name' => 'San Pelayo' ]),
            new Town(['town_code' => '807' , 'town_name' => 'Tierralta' ]),
            new Town(['town_code' => '855' , 'town_name' => 'Valencia' ])
        ]);

        $cundinamarca  = Departments::where('dept_name', 'Cundinamarca')->first();
        $cundinamarca->towns()->saveMany([
            new Town(['town_code' =>  '001', 'town_name' => 'Agua de Dios' ]),
            new Town(['town_code' =>  '019', 'town_name' => 'Alban' ]),
            new Town(['town_code' =>  '035', 'town_name' => 'Anapoima' ]),
            new Town(['town_code' =>  '040', 'town_name' => 'Anolaima' ]),
            new Town(['town_code' =>  '053', 'town_name' => 'Arbelaez' ]),
            new Town(['town_code' =>  '086', 'town_name' => 'Beltran' ]),
            new Town(['town_code' =>  '095', 'town_name' => 'Bituima' ]),
            new Town(['town_code' =>  '099', 'town_name' => 'Bojaca' ]),
            new Town(['town_code' =>  '120', 'town_name' => 'Cabrera' ]),
            new Town(['town_code' =>  '123', 'town_name' => 'Cachipay' ]),
            new Town(['town_code' =>  '126', 'town_name' => 'Cajica' ]),
            new Town(['town_code' =>  '148', 'town_name' => 'Caparrapi' ]),
            new Town(['town_code' =>  '151', 'town_name' => 'Caqueza' ]),
            new Town(['town_code' =>  '154', 'town_name' => 'Carmen de Carupa' ]),
            new Town(['town_code' =>  '168', 'town_name' => 'Chaguani' ]),
            new Town(['town_code' =>  '175', 'town_name' => 'Chia' ]),
            new Town(['town_code' =>  '178', 'town_name' => 'Chipaque' ]),
            new Town(['town_code' =>  '181', 'town_name' => 'Choachi' ]),
            new Town(['town_code' =>  '183', 'town_name' => 'Choconta' ]),
            new Town(['town_code' =>  '200', 'town_name' => 'Cogua' ]),
            new Town(['town_code' =>  '214', 'town_name' => 'Cota' ]),
            new Town(['town_code' =>  '224', 'town_name' => 'Cucunuba' ]),
            new Town(['town_code' =>  '245', 'town_name' => 'El Colegio' ]),
            new Town(['town_code' =>  '258', 'town_name' => 'El Peñon' ]),
            new Town(['town_code' =>  '260', 'town_name' => 'El Rosal' ]),
            new Town(['town_code' =>  '269', 'town_name' => 'Facatativa' ]),
            new Town(['town_code' =>  '279', 'town_name' => 'Fomeque' ]),
            new Town(['town_code' =>  '281', 'town_name' => 'Fosca' ]),
            new Town(['town_code' =>  '286', 'town_name' => 'Funza' ]),
            new Town(['town_code' =>  '288', 'town_name' => 'Fuquene' ]),
            new Town(['town_code' =>  '290', 'town_name' => 'Fusagasuga' ]),
            new Town(['town_code' =>  '293', 'town_name' => 'Gachala' ]),
            new Town(['town_code' =>  '295', 'town_name' => 'Gachancipa' ]),
            new Town(['town_code' =>  '297', 'town_name' => 'Gacheta' ]),
            new Town(['town_code' =>  '299', 'town_name' => 'Gama' ]),
            new Town(['town_code' =>  '307', 'town_name' => 'Girardot' ]),
            new Town(['town_code' =>  '312', 'town_name' => 'Granada' ]),
            new Town(['town_code' =>  '317', 'town_name' => 'Gacheta' ]),
            new Town(['town_code' =>  '320', 'town_name' => 'Guaduas' ]),
            new Town(['town_code' =>  '322', 'town_name' => 'Guasca' ]),
            new Town(['town_code' =>  '324', 'town_name' => 'Guataqui' ]),
            new Town(['town_code' =>  '326', 'town_name' => 'Guatavita' ]),
            new Town(['town_code' =>  '328', 'town_name' => 'Guayabal de Siquima' ]),
            new Town(['town_code' =>  '335', 'town_name' => 'Guayabetal' ]),
            new Town(['town_code' =>  '339', 'town_name' => 'Gutierrez' ]),
            new Town(['town_code' =>  '368', 'town_name' => 'Jerusalen' ]),
            new Town(['town_code' =>  '372', 'town_name' => 'Junin' ]),
            new Town(['town_code' =>  '377', 'town_name' => 'La Calera' ]),
            new Town(['town_code' =>  '386', 'town_name' => 'La Mesa' ]),
            new Town(['town_code' =>  '394', 'town_name' => 'La Palma' ]),
            new Town(['town_code' =>  '398', 'town_name' => 'La Peña' ]),
            new Town(['town_code' =>  '402', 'town_name' => 'La Vega' ]),
            new Town(['town_code' =>  '407', 'town_name' => 'Lenguazaque' ]),
            new Town(['town_code' =>  '426', 'town_name' => 'Macheta' ]),
            new Town(['town_code' =>  '430', 'town_name' => 'Madrid' ]),
            new Town(['town_code' =>  '436', 'town_name' => 'Manta' ]),
            new Town(['town_code' =>  '438', 'town_name' => 'Medina' ]),
            new Town(['town_code' =>  '473', 'town_name' => 'Mosquera' ]),
            new Town(['town_code' =>  '483', 'town_name' => 'Nariño' ]),
            new Town(['town_code' =>  '486', 'town_name' => 'Nemocon' ]),
            new Town(['town_code' =>  '488', 'town_name' => 'Nilo' ]),
            new Town(['town_code' =>  '489', 'town_name' => 'Nimaima' ]),
            new Town(['town_code' =>  '491', 'town_name' => 'Nocaima' ]),
            new Town(['town_code' =>  '506', 'town_name' => 'Venecia' ]),
            new Town(['town_code' =>  '513', 'town_name' => 'Pacho' ]),
            new Town(['town_code' =>  '518', 'town_name' => 'Paime' ]),
            new Town(['town_code' =>  '524', 'town_name' => 'Pandi' ]),
            new Town(['town_code' =>  '530', 'town_name' => 'Paratebueno' ]),
            new Town(['town_code' =>  '535', 'town_name' => 'Pasca' ]),
            new Town(['town_code' =>  '572', 'town_name' => 'Puerto Salgar' ]),
            new Town(['town_code' =>  '580', 'town_name' => 'Puli' ]),
            new Town(['town_code' =>  '592', 'town_name'  => 'Quebradanegra' ]),
            new Town(['town_code' =>  '594', 'town_name' => 'Quetame' ]),
            new Town(['town_code' =>  '596', 'town_name' => 'Quipile' ]),
            new Town(['town_code' =>  '599', 'town_name' => 'Apulo' ]),
            new Town(['town_code' =>  '612', 'town_name' => 'Ricaurte' ]),
            new Town(['town_code' =>  '645', 'town_name' => 'San Antonio del Tequendama' ]),
            new Town(['town_code' =>  '649', 'town_name' => 'San Bernardo' ]),
            new Town(['town_code' =>  '653', 'town_name' => 'San Cayetano' ]),
            new Town(['town_code' =>  '658', 'town_name' => 'San Francisco' ]),
            new Town(['town_code' =>  '662', 'town_name' => 'San Juan de Rioseco' ]),
            new Town(['town_code' =>  '718', 'town_name' => 'Sasaima' ]),
            new Town(['town_code' =>  '736', 'town_name' => 'Sesquile' ]),
            new Town(['town_code' =>  '740', 'town_name' => 'Sibate' ]),
            new Town(['town_code' =>  '743', 'town_name' => 'Silvania' ]),
            new Town(['town_code' =>  '745', 'town_name' => 'Simijaca' ]),
            new Town(['town_code' =>  '754', 'town_name' => 'Soacha' ]),
            new Town(['town_code' =>  '758', 'town_name' => 'Sopo' ]),
            new Town(['town_code' =>  '769', 'town_name' => 'Subachoque' ]),
            new Town(['town_code' =>  '772', 'town_name' => 'Suesca' ]),
            new Town(['town_code' =>  '777', 'town_name' => 'Supata' ]),
            new Town(['town_code' =>  '779', 'town_name' => 'Susa' ]),
            new Town(['town_code' =>  '781', 'town_name' => 'Sutatausa' ]),
            new Town(['town_code' =>  '785', 'town_name' => 'Tabio' ]),
            new Town(['town_code' =>  '793', 'town_name' => 'Tausa' ]),
            new Town(['town_code' =>  '797', 'town_name' => 'Tena' ]),
            new Town(['town_code' =>  '799', 'town_name' => 'Tenjo' ]),
            new Town(['town_code' =>  '805', 'town_name' =>'Tibacuy' ]),
            new Town(['town_code' =>  '807', 'town_name' => 'Tiribita' ]),
            new Town(['town_code' =>  '815', 'town_name' => 'Tocaima' ]),
            new Town(['town_code' =>  '817', 'town_name' => 'Tocamcipa' ]),
            new Town(['town_code' =>  '823', 'town_name' => 'Topaipi' ]),
            new Town(['town_code' =>  '839', 'town_name' => 'Ubala' ]),
            new Town(['town_code' =>  '841', 'town_name' => 'Ubaque' ]),
            new Town(['town_code' =>  '843', 'town_name' => 'Ubate' ]),
            new Town(['town_code' =>  '845', 'town_name' => 'Une' ]),
            new Town(['town_code' =>  '851', 'town_name' => 'Utica' ]),
            new Town(['town_code' =>  '862', 'town_name' => 'Vergara' ]),
            new Town(['town_code' =>  '867', 'town_name' => 'Viani' ]),
            new Town(['town_code' =>  '871', 'town_name' => 'Villagomez' ]),
            new Town(['town_code' =>  '873', 'town_name' => 'Villapinzon' ]),
            new Town(['town_code' =>  '875', 'town_name' => 'Villeta' ]),
            new Town(['town_code' =>  '878', 'town_name' => 'Viota' ]),
            new Town(['town_code' =>  '885', 'town_name' => 'Yacopi' ]),
            new Town(['town_code' =>  '898', 'town_name' => 'Zipacon' ]),
            new Town(['town_code' =>  '899', 'town_name' => 'Zipaquira' ])
        ]);

        $choco  = Departments::where('dept_name', 'Choco')->first();
        $choco->towns()->saveMany([            new Town(['town_code' => '001', 'town_name' => 'Quibdo' ]),
            new Town(['town_code' => '006', 'town_name' => 'Acandi' ]),
            new Town(['town_code' => '025', 'town_name' => 'Alto Baudo' ]),
            new Town(['town_code' => '050', 'town_name' => 'Atrato' ]),
            new Town(['town_code' => '073', 'town_name' => 'Bagado' ]),
            new Town(['town_code' => '075', 'town_name' => 'Bahia Solano' ]),
            new Town(['town_code' => '077', 'town_name' => 'Bajo Baudo' ]),
            new Town(['town_code' => '099', 'town_name' => 'Bojaya' ]),
            new Town(['town_code' => '135', 'town_name' => 'Canton de San Pablo' ]),
            new Town(['town_code' => '205', 'town_name' => 'Condoto' ]),
            new Town(['town_code' => '245', 'town_name' => 'El Carmen de Atrato' ]),
            new Town(['town_code' => '250', 'town_name' => 'Litoral del Bajo San Juan' ]),
            new Town(['town_code' => '361', 'town_name' => 'Istmina' ]),
            new Town(['town_code' => '372', 'town_name' => 'Jurado' ]),
            new Town(['town_code' => '413', 'town_name' => 'Lloro' ]),
            new Town(['town_code' => '425', 'town_name' => 'Medio Atrato' ]),
            new Town(['town_code' => '430', 'town_name' => 'Medio Baudo' ]),
            new Town(['town_code' => '491', 'town_name' => 'Novita' ]),
            new Town(['town_code' => '495', 'town_name' => 'Nuqui' ]),
            new Town(['town_code' => '600', 'town_name' => 'Rioquito' ]),
            new Town(['town_code' => '615', 'town_name' => 'Riosucio' ]),
            new Town(['town_code' => '660', 'town_name' => 'San Jose del Palmar' ]),
            new Town(['town_code' => '745', 'town_name' => 'Sipi' ]),
            new Town(['town_code' => '787', 'town_name' => 'Tado' ]),
            new Town(['town_code' => '800', 'town_name' => 'Ungia' ]),
            new Town(['town_code' => '810', 'town_name' => 'Union Panamericana' ])
        ]);

        $huila  = Departments::where('dept_name', 'Huila')->first();
        $huila->towns()->saveMany([
            new Town(['town_code' =>'001', 'town_name' => 'Neiva' ]),
            new Town(['town_code' =>'006', 'town_name' => 'Acevedo' ]),
            new Town(['town_code' =>'013', 'town_name' => 'Agrado' ]),
            new Town(['town_code' =>'016', 'town_name' => 'Aipe' ]),
            new Town(['town_code' =>'020', 'town_name' => 'Algeciras' ]),
            new Town(['town_code' =>'026', 'town_name' => 'Altamira' ]),
            new Town(['town_code' =>'078', 'town_name' => 'Baraya' ]),
            new Town(['town_code' =>'132', 'town_name' => 'Campoalegre' ]),
            new Town(['town_code' =>'206', 'town_name' => 'Colombia' ]),
            new Town(['town_code' =>'244', 'town_name' => 'Elias' ]),
            new Town(['town_code' =>'298', 'town_name' => 'Garzon' ]),
            new Town(['town_code' =>'306', 'town_name' => 'Gigante' ]),
            new Town(['town_code' =>'319', 'town_name' => 'Guadalupe' ]),
            new Town(['town_code' =>'349', 'town_name' => 'Hobo' ]),
            new Town(['town_code' =>'357', 'town_name' => 'Iquira' ]),
            new Town(['town_code' =>'359', 'town_name' => 'Isnos' ]),
            new Town(['town_code' =>'378', 'town_name' => 'La Argelia' ]),
            new Town(['town_code' =>'396', 'town_name' => 'La Plata' ]),
            new Town(['town_code' =>'483', 'town_name' => 'Nataga' ]),
            new Town(['town_code' =>'503', 'town_name' => 'Oporapa' ]),
            new Town(['town_code' =>'518', 'town_name' => 'Paicol' ]),
            new Town(['town_code' =>'524', 'town_name' => 'Palermo' ]),
            new Town(['town_code' =>'530', 'town_name' => 'Palestina' ]),
            new Town(['town_code' =>'548', 'town_name' => 'Pital' ]),
            new Town(['town_code' =>'551', 'town_name' => 'Pitalito' ]),
            new Town(['town_code' =>'615', 'town_name' => 'Rivera' ]),
            new Town(['town_code' =>'660', 'town_name' => 'Saladoblanco' ]),
            new Town(['town_code' =>'668', 'town_name' => 'San Agustin' ]),
            new Town(['town_code' =>'676', 'town_name' => 'Santa Maria' ]),
            new Town(['town_code' =>'770', 'town_name' => 'Suaza' ]),
            new Town(['town_code' =>'791', 'town_name' => 'Tarqui' ]),
            new Town(['town_code' =>'797', 'town_name' => 'Tesalia' ]),
            new Town(['town_code' =>'799', 'town_name' => 'Tello' ]),
            new Town(['town_code' =>'801', 'town_name' => 'Teruel' ]),
            new Town(['town_code' =>'807', 'town_name' => 'Timana' ]),
            new Town(['town_code' =>'872', 'town_name' => 'Villavieja' ]),
            new Town(['town_code' =>'885', 'town_name' => 'Yaguara' ])
        ]);

        $guajira  = Departments::where('dept_name', 'La Guajira')->first();
        $guajira->towns()->saveMany([
            new Town(['town_code' =>'001', 'town_name' => 'Riohacha' ]),
            new Town(['town_code' =>'078', 'town_name' => 'Barrancas' ]),
            new Town(['town_code' =>'090', 'town_name' => 'Dibulla' ]),
            new Town(['town_code' =>'098', 'town_name' => 'Distraccion' ]),
            new Town(['town_code' =>'110', 'town_name' => 'El Molino' ]),
            new Town(['town_code' =>'279', 'town_name' => 'Fonseca' ]),
            new Town(['town_code' =>'378', 'town_name' => 'Hatonuevo' ]),
            new Town(['town_code' =>'420', 'town_name' => 'La Jagua del Pilar' ]),
            new Town(['town_code' =>'430', 'town_name' => 'Maicao' ]),
            new Town(['town_code' =>'560', 'town_name' => 'Manaure' ]),
            new Town(['town_code' =>'650', 'town_name' => 'San Juan del Cesar' ]),
            new Town(['town_code' =>'847', 'town_name' => 'Uribia' ]),
            new Town(['town_code' =>'855', 'town_name' => 'Urumita' ]),
            new Town(['town_code' =>'874', 'town_name' => 'Villanueva' ])
        ]);

        $santaMarta = Departments::where('dept_name', 'Magdalena')->first();
        $santaMarta->towns()->saveMany([
            new Town(['town_code' => '001','town_name' => 'Santa Marta' ]),
            new Town(['town_code' => '030','town_name' => 'Algarrobo' ]),
            new Town(['town_code' => '053','town_name' => 'Aracataca' ]),
            new Town(['town_code' => '058','town_name' => 'Ariguani' ]),
            new Town(['town_code' => '161','town_name' => 'Cerro San Antonio' ]),
            new Town(['town_code' => '170','town_name' => 'Chivolo' ]),
            new Town(['town_code' => '189','town_name' => 'Cienaga' ]),
            new Town(['town_code' => '205','town_name' => 'Concordia' ]),
            new Town(['town_code' => '245','town_name' => 'El Banco' ]),
            new Town(['town_code' => '258','town_name' => 'El Piñon' ]),
            new Town(['town_code' => '268','town_name' => 'El Reten' ]),
            new Town(['town_code' => '288','town_name' => 'Fundacion' ]),
            new Town(['town_code' => '318','town_name' => 'Guamal' ]),
            new Town(['town_code' => '541','town_name' => 'Pedraza' ]),
            new Town(['town_code' => '545','town_name' => 'Pijiño del Carmen' ]),
            new Town(['town_code' => '551','town_name' => 'Pivijay' ]),
            new Town(['town_code' => '555','town_name' => 'Plato' ]),
            new Town(['town_code' => '570','town_name' => 'Puebloviejo' ]),
            new Town(['town_code' => '605','town_name' => 'Remolino' ]),
            new Town(['town_code' => '660','town_name' => 'Sabanas de San Miguel' ]),
            new Town(['town_code' => '675','town_name' => 'Salamina' ]),
            new Town(['town_code' => '692','town_name' => 'San Sebastian de Buenavista' ]),
            new Town(['town_code' => '703','town_name' => 'San Zenon' ]),
            new Town(['town_code' => '707','town_name' => 'Santa Ana' ]),
            new Town(['town_code' => '745','town_name' => 'Sitionuevo' ]),
            new Town(['town_code' => '798','town_name' => 'Tenerife' ])
        ]);

        $meta = Departments::where('dept_name', 'Meta')->first();
        $meta->towns()->saveMany([
            new Town(['town_code' => '001','town_name' => 'Villavicencio' ]),
            new Town(['town_code' => '006','town_name' => 'Acacias' ]),
            new Town(['town_code' => '110','town_name' => 'Barranca de Upia' ]),
            new Town(['town_code' => '124','town_name' => 'Cabuyaro' ]),
            new Town(['town_code' => '150','town_name' => 'Castilla la Nueva' ]),
            new Town(['town_code' => '223','town_name' => 'San Luis de Cubarral' ]),
            new Town(['town_code' => '226','town_name' => 'Cumaral' ]),
            new Town(['town_code' => '245','town_name' => 'El Calvario' ]),
            new Town(['town_code' => '251','town_name' => 'El Castillo' ]),
            new Town(['town_code' => '270','town_name' => 'El Dorado' ]),
            new Town(['town_code' => '287','town_name' => 'Fuente de Oro' ]),
            new Town(['town_code' => '313','town_name' => 'Granada' ]),
            new Town(['town_code' => '318','town_name' => 'Guamal' ]),
            new Town(['town_code' => '325','town_name' => 'Mapiripan' ]),
            new Town(['town_code' => '330','town_name' => 'Mesetas' ]),
            new Town(['town_code' => '350','town_name' => 'La Macarena' ]),
            new Town(['town_code' => '370','town_name' => 'La Uribe' ]),
            new Town(['town_code' => '400','town_name' => 'Lejanias' ]),
            new Town(['town_code' => '450','town_name' => 'Puerto Concordia' ]),
            new Town(['town_code' => '568','town_name' => 'Puerto Gaitan' ]),
            new Town(['town_code' => '573','town_name' => 'Puerto Lopez' ]),
            new Town(['town_code' => '577','town_name' => 'Puerto Lleras' ]),
            new Town(['town_code' => '590','town_name' => 'Puerto Rico' ]),
            new Town(['town_code' => '606','town_name' => 'Restrepo' ]),
            new Town(['town_code' => '680','town_name' => 'San Carlos de Guaroa' ]),
            new Town(['town_code' => '683','town_name' => 'San Juan de Arama' ]),
            new Town(['town_code' => '686','town_name' => 'San Juanito' ]),
            new Town(['town_code' => '689','town_name' => 'San Martin' ]),
            new Town(['town_code' => '711','town_name' => 'Vista Hermosa' ])
        ]);

        $pasto = Departments::where('dept_name', 'Nariño')->first();
        $pasto->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Pasto' ]),
            new Town(['town_code' => '019', 'town_name' => 'Alban' ]),
            new Town(['town_code' => '022', 'town_name' => 'Aldana' ]),
            new Town(['town_code' => '036', 'town_name' => 'Ancuya' ]),
            new Town(['town_code' => '051', 'town_name' => 'Arboleda' ]),
            new Town(['town_code' => '079', 'town_name' => 'Barbacoas' ]),
            new Town(['town_code' => '083', 'town_name' => 'Belen' ]),
            new Town(['town_code' => '110', 'town_name' => 'Buesaco' ]),
            new Town(['town_code' => '203', 'town_name' => 'Colon' ]),
            new Town(['town_code' => '207', 'town_name' => 'Consaca' ]),
            new Town(['town_code' => '210', 'town_name' => 'Contadero' ]),
            new Town(['town_code' => '215', 'town_name' => 'Cordoba' ]),
            new Town(['town_code' => '224', 'town_name' => 'Cuaspud' ]),
            new Town(['town_code' => '227', 'town_name' => 'Cumbal' ]),
            new Town(['town_code' => '233', 'town_name' => 'Cumbitara' ]),
            new Town(['town_code' => '240', 'town_name' => 'Chachagui' ]),
            new Town(['town_code' => '250', 'town_name' => 'El Charco' ]),
            new Town(['town_code' => '254', 'town_name' => 'El Peñol' ]),
            new Town(['town_code' => '256', 'town_name' => 'El Rosario' ]),
            new Town(['town_code' => '258', 'town_name' => 'El Tablon' ]),
            new Town(['town_code' => '260', 'town_name' => 'El Tambo' ]),
            new Town(['town_code' => '287', 'town_name' => 'Funes' ]),
            new Town(['town_code' => '317', 'town_name' => 'Guachucal' ]),
            new Town(['town_code' => '320', 'town_name' => 'Guaitarilla' ]),
            new Town(['town_code' => '323', 'town_name' => 'Gualmatan' ]),
            new Town(['town_code' => '352', 'town_name' => 'Iles' ]),
            new Town(['town_code' => '354', 'town_name' => 'Imues' ]),
            new Town(['town_code' => '356', 'town_name' => 'Ipiales' ]),
            new Town(['town_code' => '378', 'town_name' => 'La Cruz' ]),
            new Town(['town_code' => '381', 'town_name' => 'La Florida' ]),
            new Town(['town_code' => '385', 'town_name' => 'La Llanada' ]),
            new Town(['town_code' => '390', 'town_name' => 'La Tola' ]),
            new Town(['town_code' => '399', 'town_name' => 'La Union' ]),
            new Town(['town_code' => '405', 'town_name' => 'Leiva' ]),
            new Town(['town_code' => '411', 'town_name' => 'Linares' ]),
            new Town(['town_code' => '418', 'town_name' => 'Los Andes' ]),
            new Town(['town_code' => '427', 'town_name' => 'Magui' ]),
            new Town(['town_code' => '435', 'town_name' => 'Mallama' ]),
            new Town(['town_code' => '473', 'town_name' => 'Mosquera' ]),
            new Town(['town_code' => '490', 'town_name' => 'Olaya Herrera' ]),
            new Town(['town_code' => '506', 'town_name' => 'Ospina' ]),
            new Town(['town_code' => '520', 'town_name' => 'Francisco Pizarro' ]),
            new Town(['town_code' => '540', 'town_name' => 'Policarpa' ]),
            new Town(['town_code' => '560', 'town_name' => 'Potosi' ]),
            new Town(['town_code' => '565', 'town_name' => 'Providencia' ]),
            new Town(['town_code' => '573', 'town_name' => 'Puerres' ]),
            new Town(['town_code' => '585', 'town_name' => 'Rupiales' ]),
            new Town(['town_code' => '612', 'town_name' => 'Ricaurte' ]),
            new Town(['town_code' => '621', 'town_name' => 'Roberto Payan' ]),
            new Town(['town_code' => '678', 'town_name' => 'Samaniego' ]),
            new Town(['town_code' => '683', 'town_name' => 'Sandona' ]),
            new Town(['town_code' => '685', 'town_name' => 'San Bernardo' ]),
            new Town(['town_code' => '687', 'town_name' => 'San Lorenzo' ]),
            new Town(['town_code' => '693', 'town_name' => 'San Pablo' ]),
            new Town(['town_code' => '694', 'town_name' => 'San Pedro de Cartago' ]),
            new Town(['town_code' => '696', 'town_name' => 'Santa Barbara' ]),
            new Town(['town_code' => '699', 'town_name' => 'Santa Cruz' ]),
            new Town(['town_code' => '720', 'town_name' => 'Sapuyes' ]),
            new Town(['town_code' => '786', 'town_name' => 'Taminango' ]),
            new Town(['town_code' => '788', 'town_name' => 'Tangua' ]),
            new Town(['town_code' => '835', 'town_name' => 'Tumaco' ]),
            new Town(['town_code' => '838', 'town_name' => 'Tuquerres' ]),
            new Town(['town_code' => '885', 'town_name' => 'Yacuanquer' ])
        ]);

        $NdeSantander = Departments::where('dept_name', 'Norte de Santander')->first();
        $NdeSantander->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Cucuta' ]),
            new Town(['town_code' => '003', 'town_name' => 'Abrego' ]),
            new Town(['town_code' => '051', 'town_name' => 'Arboledas' ]),
            new Town(['town_code' => '099', 'town_name' => 'Bochalema' ]),
            new Town(['town_code' => '109', 'town_name' => 'Bucarasica' ]),
            new Town(['town_code' => '125', 'town_name' => 'Cacota' ]),
            new Town(['town_code' => '128', 'town_name' => 'Cachira' ]),
            new Town(['town_code' => '172', 'town_name' => 'Chinacota' ]),
            new Town(['town_code' => '174', 'town_name' => 'Chitaga' ]),
            new Town(['town_code' => '206', 'town_name' => 'Convencion' ]),
            new Town(['town_code' => '223', 'town_name' => 'Cucutilla' ]),
            new Town(['town_code' => '239', 'town_name' => 'Durania' ]),
            new Town(['town_code' => '245', 'town_name' => 'El Carmen' ]),
            new Town(['town_code' => '250', 'town_name' => 'El Tarra' ]),
            new Town(['town_code' => '261', 'town_name' => 'El Zulia' ]),
            new Town(['town_code' => '313', 'town_name' => 'Gramalote' ]),
            new Town(['town_code' => '344', 'town_name' => 'Hacari' ]),
            new Town(['town_code' => '347', 'town_name' => 'Herran' ]),
            new Town(['town_code' => '377', 'town_name' => 'Labateca' ]),
            new Town(['town_code' => '385', 'town_name' => 'La Esperanza' ]),
            new Town(['town_code' => '398', 'town_name' => 'La Playa' ]),
            new Town(['town_code' => '405', 'town_name' => 'Los Patios' ]),
            new Town(['town_code' => '418', 'town_name' => 'Lourdes' ]),
            new Town(['town_code' => '480', 'town_name' => 'Mutiscua' ]),
            new Town(['town_code' => '498', 'town_name' => 'Ocaña' ]),
            new Town(['town_code' => '518', 'town_name' => 'Pamplona' ]),
            new Town(['town_code' => '520', 'town_name' => 'Pamplonita' ]),
            new Town(['town_code' => '553', 'town_name' => 'Puerto Santander' ]),
            new Town(['town_code' => '599', 'town_name' => 'Ragonvalia' ]),
            new Town(['town_code' => '660', 'town_name' => 'Salazar' ]),
            new Town(['town_code' => '670', 'town_name' => 'San Calixto' ]),
            new Town(['town_code' => '673', 'town_name' => 'San Cayetano' ]),
            new Town(['town_code' => '680', 'town_name' => 'Santiago' ]),
            new Town(['town_code' => '720', 'town_name' => 'Sardinata' ]),
            new Town(['town_code' => '743', 'town_name' => 'Silos' ]),
            new Town(['town_code' => '800', 'town_name' => 'Teorama' ]),
            new Town(['town_code' => '810', 'town_name' => 'Tibu' ]),
            new Town(['town_code' => '820', 'town_name' => 'Toledo' ]),
            new Town(['town_code' => '871', 'town_name' => 'Villacaro' ]),
            new Town(['town_code' => '874', 'town_name' => 'Villa del Rosario' ])
        ]);

        $quindio = Departments::where('dept_name', 'Quindio')->first();
        $quindio->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Armenia' ]),
            new Town(['town_code' => '111', 'town_name' => 'Buenavista' ]),
            new Town(['town_code' => '130', 'town_name' => 'Calarca' ]),
            new Town(['town_code' => '190', 'town_name' => 'Circasia' ]),
            new Town(['town_code' => '212', 'town_name' => 'Cordoba' ]),
            new Town(['town_code' => '272', 'town_name' => 'Filandia' ]),
            new Town(['town_code' => '302', 'town_name' => 'Genova' ]),
            new Town(['town_code' => '401', 'town_name' => 'La Tebaida' ]),
            new Town(['town_code' => '470', 'town_name' => 'Montenegro' ]),
            new Town(['town_code' => '548', 'town_name' => 'Pijao' ]),
            new Town(['town_code' => '594', 'town_name' => 'Quimbaya' ]),
            new Town(['town_code' => '690', 'town_name' => 'Salento' ])
        ]);

        $risaralda = Departments::where('dept_name', 'Risaralda')->first();
        $risaralda->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Pereira' ]),
            new Town(['town_code' => '045', 'town_name' => 'Apia' ]),
            new Town(['town_code' => '075', 'town_name' => 'Balboa' ]),
            new Town(['town_code' => '088', 'town_name' => 'Belen de Umbria' ]),
            new Town(['town_code' => '170', 'town_name' => 'Dos Quebradas' ]),
            new Town(['town_code' => '318', 'town_name' => 'Guatica' ]),
            new Town(['town_code' => '383', 'town_name' => 'La Celia' ]),
            new Town(['town_code' => '400', 'town_name' => 'La Virginia' ]),
            new Town(['town_code' => '440', 'town_name' => 'Marsella' ]),
            new Town(['town_code' => '456', 'town_name' => 'Mistrato' ]),
            new Town(['town_code' => '572', 'town_name' => 'Pueblo Rico' ]),
            new Town(['town_code' => '594', 'town_name' => 'Quinchia' ]),
            new Town(['town_code' => '682', 'town_name' => 'Santa Rosa de Cabal' ]),
            new Town(['town_code' => '687', 'town_name' => 'Santuario' ])
        ]);

        $santander = Departments::where('dept_name', 'Santander')->first();
        $santander->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Bucaramanga' ]),
            new Town(['town_code' => '013', 'town_name' => 'Aguada' ]),
            new Town(['town_code' => '020', 'town_name' => 'Albania' ]),
            new Town(['town_code' => '051', 'town_name' => 'Aratoca' ]),
            new Town(['town_code' => '077', 'town_name' => 'Barbosa' ]),
            new Town(['town_code' => '079', 'town_name' => 'Barichara' ]),
            new Town(['town_code' => '081', 'town_name' => 'Barrancabermeja' ]),
            new Town(['town_code' => '092', 'town_name' => 'Betulia' ]),
            new Town(['town_code' => '101', 'town_name' => 'Bolivar' ]),
            new Town(['town_code' => '121', 'town_name' => 'Cabrera' ]),
            new Town(['town_code' => '132', 'town_name' => 'California' ]),
            new Town(['town_code' => '147', 'town_name' => 'Capitanejo' ]),
            new Town(['town_code' => '152', 'town_name' => 'Carcasi' ]),
            new Town(['town_code' => '160', 'town_name' => 'Cepita' ]),
            new Town(['town_code' => '162', 'town_name' => 'Cerrito' ]),
            new Town(['town_code' => '167', 'town_name' => 'Charala' ]),
            new Town(['town_code' => '169', 'town_name' => 'Charta' ]),
            new Town(['town_code' => '176', 'town_name' => 'Chima' ]),
            new Town(['town_code' => '179', 'town_name' => 'Chipata' ]),
            new Town(['town_code' => '190', 'town_name' => 'Cimitarra' ]),
            new Town(['town_code' => '207', 'town_name' => 'Concepcion' ]),
            new Town(['town_code' => '209', 'town_name' => 'Confines' ]),
            new Town(['town_code' => '211', 'town_name' => 'Contratacion' ]),
            new Town(['town_code' => '217', 'town_name' => 'Coromoro' ]),
            new Town(['town_code' => '229', 'town_name' => 'Curiti' ]),
            new Town(['town_code' => '235', 'town_name' => 'EL Carmen de Chucury' ]),
            new Town(['town_code' => '245', 'town_name' => 'El Guacamayo' ]),
            new Town(['town_code' => '250', 'town_name' => 'El Peñon' ]),
            new Town(['town_code' => '255', 'town_name' => 'El Playon' ]),
            new Town(['town_code' => '264', 'town_name' => 'Encino' ]),
            new Town(['town_code' => '266', 'town_name' => 'Enciso' ]),
            new Town(['town_code' => '271', 'town_name' => 'Florian' ]),
            new Town(['town_code' => '276', 'town_name' => 'Floridablanca' ]),
            new Town(['town_code' => '296', 'town_name' => 'Galan' ]),
            new Town(['town_code' => '298', 'town_name' => 'Gambita' ]),
            new Town(['town_code' => '307', 'town_name' => 'Giron' ]),
            new Town(['town_code' => '318', 'town_name' => 'Guaca' ]),
            new Town(['town_code' => '320', 'town_name' => 'Guadalupe' ]),
            new Town(['town_code' => '322', 'town_name' => 'Guapota' ]),
            new Town(['town_code' => '327', 'town_name' => 'Guepsa' ]),
            new Town(['town_code' => '344', 'town_name' => 'Hato' ]),
            new Town(['town_code' => '368', 'town_name' => 'Jesus Maria' ]),
            new Town(['town_code' => '370', 'town_name' => 'Jordan' ]),
            new Town(['town_code' => '377', 'town_name' => 'La Belleza' ]),
            new Town(['town_code' => '385', 'town_name' => 'Landazuri' ]),
            new Town(['town_code' => '397', 'town_name' => 'La Paz' ]),
            new Town(['town_code' => '406', 'town_name' => 'Lebrija' ]),
            new Town(['town_code' => '418', 'town_name' => 'Los Santos' ]),
            new Town(['town_code' => '425', 'town_name' => 'Macaravita' ]),
            new Town(['town_code' => '432', 'town_name' => 'Malaga' ]),
            new Town(['town_code' => '444', 'town_name' => 'Matanza' ]),
            new Town(['town_code' => '464', 'town_name' => 'Mogotes' ]),
            new Town(['town_code' => '468', 'town_name' => 'Molagavita' ]),
            new Town(['town_code' => '498', 'town_name' => 'Ocamonte' ]),
            new Town(['town_code' => '500', 'town_name' => 'Oiba' ]),
            new Town(['town_code' => '502', 'town_name' => 'Onzaga' ]),
            new Town(['town_code' => '522', 'town_name' => 'Palmar' ]),
            new Town(['town_code' => '524', 'town_name' => 'Palmas del Socorro' ]),
            new Town(['town_code' => '533', 'town_name' => 'Paramo' ]),
            new Town(['town_code' => '547', 'town_name' => 'Piedecuesta' ]),
            new Town(['town_code' => '549', 'town_name' => 'Pinchote' ]),
            new Town(['town_code' => '572', 'town_name' => 'Puente Nacional' ]),
            new Town(['town_code' => '573', 'town_name' => 'Puerto Parra' ]),
            new Town(['town_code' => '575', 'town_name' => 'Puerto Wilches' ]),
            new Town(['town_code' => '615', 'town_name' => 'Rionegro' ]),
            new Town(['town_code' => '655', 'town_name' => 'Sabana de Torres' ]),
            new Town(['town_code' => '669', 'town_name' => 'San Andres' ]),
            new Town(['town_code' => '673', 'town_name' => 'San Benito' ]),
            new Town(['town_code' => '679', 'town_name' => 'San Gil' ]),
            new Town(['town_code' => '682', 'town_name' => 'San Joaquin' ]),
            new Town(['town_code' => '684', 'town_name' => 'San Jose de Miranda' ]),
            new Town(['town_code' => '686', 'town_name' => 'San Miguel' ]),
            new Town(['town_code' => '689', 'town_name' => 'San Vicente de Chucuri' ]),
            new Town(['town_code' => '705', 'town_name' => 'Santa Barbara' ]),
            new Town(['town_code' => '720', 'town_name' => 'Santa Helena del Opon' ]),
            new Town(['town_code' => '745', 'town_name' => 'Simacota' ]),
            new Town(['town_code' => '755', 'town_name' => 'Socorro' ]),
            new Town(['town_code' => '770', 'town_name' => 'Suaita' ]),
            new Town(['town_code' => '773', 'town_name' => 'Sucre' ]),
            new Town(['town_code' => '780', 'town_name' => 'Surata' ]),
            new Town(['town_code' => '820', 'town_name' => 'Tona' ]),
            new Town(['town_code' => '855', 'town_name' => 'Valle San Jose' ]),
            new Town(['town_code' => '861', 'town_name' => 'Velez' ]),
            new Town(['town_code' => '867', 'town_name' => 'Vetas' ]),
            new Town(['town_code' => '872', 'town_name' => 'Villanueva' ]),
            new Town(['town_code' => '895', 'town_name' => 'Zapatoca '])
        ]);

        $sucre = Departments::where('dept_name', 'Sucre')->first();
        $sucre->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Sincelejo' ]),
            new Town(['town_code' => '110', 'town_name' => 'Buenavista' ]),
            new Town(['town_code' => '124', 'town_name' => 'Caimito' ]),
            new Town(['town_code' => '204', 'town_name' => 'Coloso' ]),
            new Town(['town_code' => '215', 'town_name' => 'Corozal' ]),
            new Town(['town_code' => '230', 'town_name' => 'Chalan' ]),
            new Town(['town_code' => '235', 'town_name' => 'Galeras' ]),
            new Town(['town_code' => '265', 'town_name' => 'Guaranda' ]),
            new Town(['town_code' => '400', 'town_name' => 'La Union' ]),
            new Town(['town_code' => '418', 'town_name' => 'Los Palmitos' ]),
            new Town(['town_code' => '429', 'town_name' => 'Majagual' ]),
            new Town(['town_code' => '473', 'town_name' => 'Morroa' ]),
            new Town(['town_code' => '508', 'town_name' => 'Ovejas' ]),
            new Town(['town_code' => '523', 'town_name' => 'Palmito' ]),
            new Town(['town_code' => '670', 'town_name' => 'Sampues' ]),
            new Town(['town_code' => '678', 'town_name' => 'San Benito Abad' ]),
            new Town(['town_code' => '702', 'town_name' => 'San Juan de Betulia' ]),
            new Town(['town_code' => '708', 'town_name' => 'San Marcos' ]),
            new Town(['town_code' => '713', 'town_name' => 'San Onofre' ]),
            new Town(['town_code' => '742', 'town_name' => 'Since' ]),
            new Town(['town_code' => '771', 'town_name' => 'Sucre' ]),
            new Town(['town_code' => '820', 'town_name' => 'Tolu' ]),
            new Town(['town_code' => '823', 'town_name' => 'Toluviejo' ])
        ]);

        $tolima = Departments::where('dept_name', 'Tolima')->first();
        $tolima->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Ibague' ]),
            new Town(['town_code' => '024', 'town_name' => 'Alpujarra' ]),
            new Town(['town_code' => '026', 'town_name' => 'Alvarado' ]),
            new Town(['town_code' => '030', 'town_name' => 'Ambalema' ]),
            new Town(['town_code' => '043', 'town_name' => 'Anzoategui' ]),
            new Town(['town_code' => '055', 'town_name' => 'Armero' ]),
            new Town(['town_code' => '067', 'town_name' => 'Ataco' ]),
            new Town(['town_code' => '124', 'town_name' => 'Cajamarca' ]),
            new Town(['town_code' => '148', 'town_name' => 'Carmen Apicala' ]),
            new Town(['town_code' => '152', 'town_name' => 'Casabianca' ]),
            new Town(['town_code' => '168', 'town_name' => 'Chaparral' ]),
            new Town(['town_code' => '200', 'town_name' => 'Coello' ]),
            new Town(['town_code' => '217', 'town_name' => 'Coyaima' ]),
            new Town(['town_code' => '226', 'town_name' => 'Cunday' ]),
            new Town(['town_code' => '236', 'town_name' => 'Dolores' ]),
            new Town(['town_code' => '268', 'town_name' => 'Espinal' ]),
            new Town(['town_code' => '270', 'town_name' => 'Falan' ]),
            new Town(['town_code' => '275', 'town_name' => 'Flandes' ]),
            new Town(['town_code' => '283', 'town_name' => 'Fresno' ]),
            new Town(['town_code' => '319', 'town_name' => 'Guamo' ]),
            new Town(['town_code' => '347', 'town_name' => 'Herveo' ]),
            new Town(['town_code' => '349', 'town_name' => 'Honda' ]),
            new Town(['town_code' => '352', 'town_name' => 'Icononzo' ]),
            new Town(['town_code' => '408', 'town_name' => 'Lerida' ]),
            new Town(['town_code' => '411', 'town_name' => 'Libano' ]),
            new Town(['town_code' => '443', 'town_name' => 'Mariquita' ]),
            new Town(['town_code' => '449', 'town_name' => 'Melgar' ]),
            new Town(['town_code' => '461', 'town_name' => 'Murillo' ]),
            new Town(['town_code' => '483', 'town_name' => 'Natagaima' ]),
            new Town(['town_code' => '504', 'town_name' => 'Ortega' ]),
            new Town(['town_code' => '520', 'town_name' => 'Palocabildo' ]),
            new Town(['town_code' => '547', 'town_name' => 'Piedras' ]),
            new Town(['town_code' => '555', 'town_name' => 'Planadas' ]),
            new Town(['town_code' => '563', 'town_name' => 'Prado' ]),
            new Town(['town_code' => '585', 'town_name' => 'Purificacion' ]),
            new Town(['town_code' => '616', 'town_name' => 'Rioblanco' ]),
            new Town(['town_code' => '622', 'town_name' => 'Roncesvalles' ]),
            new Town(['town_code' => '624', 'town_name' => 'Rovira' ]),
            new Town(['town_code' => '671', 'town_name' => 'Saldaña' ]),
            new Town(['town_code' => '675', 'town_name' => 'San Antonio' ]),
            new Town(['town_code' => '678', 'town_name' => 'San Luis' ]),
            new Town(['town_code' => '686', 'town_name' => 'Santa Isabel' ]),
            new Town(['town_code' => '770', 'town_name' => 'Suarez' ]),
            new Town(['town_code' => '854', 'town_name' => 'Valle de San Juan' ]),
            new Town(['town_code' => '861', 'town_name' => 'Venadillo' ]),
            new Town(['town_code' => '870', 'town_name' => 'Villahermosa' ]),
            new Town(['town_code' => '873', 'town_name' => 'Villarica' ])
        ]);

        $valle = Departments::where('dept_name', 'Valle del Cauca')->first();
        $valle->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Santiago de Cali' ]),
            new Town(['town_code' => '020', 'town_name' => 'Alcala' ]),
            new Town(['town_code' => '036', 'town_name' => 'Andalucia' ]),
            new Town(['town_code' => '041', 'town_name' => 'Ansermanuevo' ]),
            new Town(['town_code' => '054', 'town_name' => 'Argelia' ]),
            new Town(['town_code' => '100', 'town_name' => 'Bolivar' ]),
            new Town(['town_code' => '109', 'town_name' => 'Buenaventura' ]),
            new Town(['town_code' => '111', 'town_name' => 'Buga' ]),
            new Town(['town_code' => '113', 'town_name' => 'Bugalagrande' ]),
            new Town(['town_code' => '122', 'town_name' => 'Caicedonia' ]),
            new Town(['town_code' => '126', 'town_name' => 'Calima' ]),
            new Town(['town_code' => '130', 'town_name' => 'Candelaria' ]),
            new Town(['town_code' => '147', 'town_name' => 'Cartago' ]),
            new Town(['town_code' => '233', 'town_name' => 'Dagua' ]),
            new Town(['town_code' => '243', 'town_name' => 'El Aguila' ]),
            new Town(['town_code' => '246', 'town_name' => 'El Cairo' ]),
            new Town(['town_code' => '248', 'town_name' => 'El Cerrito' ]),
            new Town(['town_code' => '250', 'town_name' => 'El Dovio' ]),
            new Town(['town_code' => '275', 'town_name' => 'Florida' ]),
            new Town(['town_code' => '306', 'town_name' => 'Ginebra' ]),
            new Town(['town_code' => '318', 'town_name' => 'Guacari' ]),
            new Town(['town_code' => '364', 'town_name' => 'Jamundi' ]),
            new Town(['town_code' => '377', 'town_name' => 'La Cumbre' ]),
            new Town(['town_code' => '400', 'town_name' => 'La Union' ]),
            new Town(['town_code' => '403', 'town_name' => 'La Victoria' ]),
            new Town(['town_code' => '497', 'town_name' => 'Obando' ]),
            new Town(['town_code' => '520', 'town_name' => 'Palmira' ]),
            new Town(['town_code' => '563', 'town_name' => 'Pradera' ]),
            new Town(['town_code' => '606', 'town_name' => 'Restrepo' ]),
            new Town(['town_code' => '616', 'town_name' => 'Riofrio' ]),
            new Town(['town_code' => '622', 'town_name' => 'Ronaldillo' ]),
            new Town(['town_code' => '670', 'town_name' => 'San Pedro' ]),
            new Town(['town_code' => '736', 'town_name' => 'Sevilla' ]),
            new Town(['town_code' => '823', 'town_name' => 'Toro' ]),
            new Town(['town_code' => '828', 'town_name' => 'Trujillo' ]),
            new Town(['town_code' => '834', 'town_name' => 'Tulua' ]),
            new Town(['town_code' => '845', 'town_name' => 'Ulloa' ]),
            new Town(['town_code' => '863', 'town_name' => 'Versalles' ]),
            new Town(['town_code' => '869', 'town_name' => 'Vijes' ]),
            new Town(['town_code' => '890', 'town_name' => 'Yotoco' ]),
            new Town(['town_code' => '892', 'town_name' => 'Yumbo' ]),
            new Town(['town_code' => '895', 'town_name' => 'Zarzal' ])
        ]);

        $arauca = Departments::where('dept_name', 'Arauca')->first();
        $arauca->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Arauca' ]),
            new Town(['town_code' => '065', 'town_name' => 'Arauquita' ]),
            new Town(['town_code' => '220', 'town_name' => 'Cravo Norte' ]),
            new Town(['town_code' => '300', 'town_name' => 'Fortul' ]),
            new Town(['town_code' => '591', 'town_name' => 'Puerto Rondon' ]),
            new Town(['town_code' => '736', 'town_name' => 'Saravena' ]),
            new Town(['town_code' => '794', 'town_name' => 'Tame' ])
        ]);

        $casanare = Departments::where('dept_name', 'Casanare')->first();
        $casanare->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Yopal' ]),
            new Town(['town_code' => '010', 'town_name' => 'Aguazul' ]),
            new Town(['town_code' => '015', 'town_name' => 'Chameza' ]),
            new Town(['town_code' => '125', 'town_name' => 'Hato Corozal' ]),
            new Town(['town_code' => '136', 'town_name' => 'La Salina' ]),
            new Town(['town_code' => '139', 'town_name' => 'Mani' ]),
            new Town(['town_code' => '162', 'town_name' => 'Monterrey' ]),
            new Town(['town_code' => '225', 'town_name' => 'Nunchia' ]),
            new Town(['town_code' => '230', 'town_name' => 'Orocue' ]),
            new Town(['town_code' => '250', 'town_name' => 'Paz de Ariporo' ]),
            new Town(['town_code' => '263', 'town_name' => 'Pore' ]),
            new Town(['town_code' => '279', 'town_name' => 'Recetor' ]),
            new Town(['town_code' => '300', 'town_name' => 'Sabanalarga' ]),
            new Town(['town_code' => '315', 'town_name' => 'Sacama' ]),
            new Town(['town_code' => '325', 'town_name' => 'San Luis de Palenque' ]),
            new Town(['town_code' => '400', 'town_name' => 'Tamara' ]),
            new Town(['town_code' => '410', 'town_name' => 'Tauramena' ]),
            new Town(['town_code' => '430', 'town_name' => 'Trinidad' ]),
            new Town(['town_code' => '440', 'town_name' => 'Villanueva' ]),
        ]);

        $putumayo = Departments::where('dept_name', 'Putumayo')->first();
        $putumayo->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Mocoa' ]),
            new Town(['town_code' => '219', 'town_name' => 'Colon' ]),
            new Town(['town_code' => '320', 'town_name' => 'Orito' ]),
            new Town(['town_code' => '568', 'town_name' => 'Puerto Asis' ]),
            new Town(['town_code' => '569', 'town_name' => 'Puerto Caicedo' ]),
            new Town(['town_code' => '571', 'town_name' => 'Puerto Guzman' ]),
            new Town(['town_code' => '573', 'town_name' => 'Puerto Leguizamo' ]),
            new Town(['town_code' => '749', 'town_name' => 'Sibundoy' ]),
            new Town(['town_code' => '755', 'town_name' => 'San Francisco' ]),
            new Town(['town_code' => '757', 'town_name' => 'San Miguel' ]),
            new Town(['town_code' => '760', 'town_name' => 'Santiago' ]),
            new Town(['town_code' => '865', 'town_name' => 'La Hormiga' ]),
            new Town(['town_code' => '885', 'town_name' => 'Villagarzon' ]),
        ]);

        $sanAndres = Departments::where('dept_name', 'San Andres')->first();
        $sanAndres->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'San Andres' ]),
            new Town(['town_code' => '564', 'town_name' => 'Providencia' ])
        ]);

        $leticia = Departments::where('dept_name', 'Amazonas')->first();
        $leticia->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Leticia' ]),
            new Town(['town_code' => '263', 'town_name' => 'El Encanto' ]),
            new Town(['town_code' => '405', 'town_name' => 'La Chorrera' ]),
            new Town(['town_code' => '407', 'town_name' => 'La Pedrera' ]),
            new Town(['town_code' => '430', 'town_name' => 'La Victoria' ]),
            new Town(['town_code' => '460', 'town_name' => 'Miriti-Parana' ]),
            new Town(['town_code' => '530', 'town_name' => 'Puerto Alegria' ]),
            new Town(['town_code' => '536', 'town_name' => 'Puerto Arica' ]),
            new Town(['town_code' => '540', 'town_name' => 'Puerto Nariño' ]),
            new Town(['town_code' => '669', 'town_name' => 'Puerto Santander' ]),
            new Town(['town_code' => '798', 'town_name' => 'Tarapaca' ])
        ]);

        $guainia = Departments::where('dept_name', 'Guainia')->first();
        $guainia->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Puerto Inirida' ]),
            new Town(['town_code' => '343', 'town_name' => 'Barranco Minas' ]),
            new Town(['town_code' => '883', 'town_name' => 'San Felipe' ]),
            new Town(['town_code' => '884', 'town_name' => 'Puerto Colombia' ]),
            new Town(['town_code' => '885', 'town_name' => 'La Guadalupe' ]),
            new Town(['town_code' => '886', 'town_name' => 'Cacahual' ]),
            new Town(['town_code' => '887', 'town_name' => 'Pana Pana' ]),
            new Town(['town_code' => '888', 'town_name' => 'Morichal' ])
        ]);

        $guaviare = Departments::where('dept_name', 'Guaviare')->first();
        $guaviare->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'San Jose del Guaviare' ]),
            new Town(['town_code' => '015', 'town_name' => 'Calamar' ]),
            new Town(['town_code' => '025', 'town_name' => 'El Retorno' ]),
            new Town(['town_code' => '200', 'town_name' => 'Miraflorez' ])
        ]);

        $vaupes = Departments::where('dept_name', 'Vaupes')->first();
        $vaupes->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Mitu' ]),
            new Town(['town_code' => '161', 'town_name' => 'Caruru' ]),
            new Town(['town_code' => '511', 'town_name' => 'Pacoa' ]),
            new Town(['town_code' => '666', 'town_name' => 'Taraira' ]),
            new Town(['town_code' => '777', 'town_name' => 'Papunaua' ]),
            new Town(['town_code' => '889', 'town_name' => 'Yavarete' ])
        ]);

        $vichada = Departments::where('dept_name', 'Vichada')->first();
        $vichada->towns()->saveMany([
            new Town(['town_code' => '001', 'town_name' => 'Puerto Carreño' ]),
            new Town(['town_code' => '524', 'town_name' => 'La Primavera' ]),
            new Town(['town_code' => '572', 'town_name' => 'Santa Rita' ]),
            new Town(['town_code' => '666', 'town_name' => 'Santa Rosalia' ]),
            new Town(['town_code' => '760', 'town_name' => 'San Jose de Ocune' ]),
            new Town(['town_code' => '773', 'town_name' => 'Cumarabo' ])
        ]);















    }
}
